export const ContractAbi = [
   {
      "inputs":[
         {
            "internalType":"uint16",
            "name":"_feeInBasisPoints",
            "type":"uint16"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"owner",
            "type":"address"
         }
      ],
      "name":"OwnableInvalidOwner",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"OwnableUnauthorizedAccount",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"PayStreams__AddressZero",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"PayStreams__InsufficientCollectedFees",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"uint16",
            "name":"feeInBasisPoints",
            "type":"uint16"
         }
      ],
      "name":"PayStreams__InvalidFeeInBasisPoints",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"PayStreams__InvalidStreamConfig",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"PayStreams__InvalidUpdateParams",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"streamHash",
            "type":"bytes32"
         }
      ],
      "name":"PayStreams__StreamAlreadyExists",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"streamHash",
            "type":"bytes32"
         },
         {
            "internalType":"uint256",
            "name":"startingTimestamp",
            "type":"uint256"
         }
      ],
      "name":"PayStreams__StreamHasNotStartedYet",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"PayStreams__Unauthorized",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         }
      ],
      "name":"PayStreams__UnsupportedToken",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"PayStreams__ZeroAmountToCollect",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         }
      ],
      "name":"SafeERC20FailedOperation",
      "type":"error"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"uint16",
            "name":"_feeInBasisPoints",
            "type":"uint16"
         }
      ],
      "name":"FeeInBasisPointsSet",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"newFeeRecipient",
            "type":"address"
         }
      ],
      "name":"FeeRecipientSet",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"token",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"FeesCollected",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"streamHash",
            "type":"bytes32"
         },
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"amountToCollect",
            "type":"uint256"
         }
      ],
      "name":"FundsCollectedFromStream",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"by",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"streamHash",
            "type":"bytes32"
         }
      ],
      "name":"HookConfigSet",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"previousOwner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferred",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"streamHash",
            "type":"bytes32"
         }
      ],
      "name":"StreamCancelled",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"streamHash",
            "type":"bytes32"
         }
      ],
      "name":"StreamCreated",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"streamHash",
            "type":"bytes32"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"startingTimestamp",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"duration",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"bool",
            "name":"recurring",
            "type":"bool"
         }
      ],
      "name":"StreamUpdated",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"token",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"bool",
            "name":"support",
            "type":"bool"
         }
      ],
      "name":"TokenSet",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"by",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"streamHash",
            "type":"bytes32"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"vault",
            "type":"address"
         }
      ],
      "name":"VaultSet",
      "type":"event"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_streamHash",
            "type":"bytes32"
         }
      ],
      "name":"cancelStream",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_token",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"collectFees",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_streamHash",
            "type":"bytes32"
         }
      ],
      "name":"collectFundsFromStream",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_streamHash",
            "type":"bytes32"
         }
      ],
      "name":"getAmountToCollectFromStreamAndFeeToPay",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_token",
            "type":"address"
         }
      ],
      "name":"getCollectedFees",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getFeeInBasisPoints",
      "outputs":[
         {
            "internalType":"uint16",
            "name":"",
            "type":"uint16"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "internalType":"bytes32",
            "name":"_streamHash",
            "type":"bytes32"
         }
      ],
      "name":"getHookConfig",
      "outputs":[
         {
            "components":[
               {
                  "internalType":"bool",
                  "name":"callAfterStreamCreated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeFundsCollected",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterFundsCollected",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeStreamUpdated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterStreamUpdated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeStreamClosed",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterStreamClosed",
                  "type":"bool"
               }
            ],
            "internalType":"struct IPayStreams.HookConfig",
            "name":"",
            "type":"tuple"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_recipient",
            "type":"address"
         }
      ],
      "name":"getRecipientStreamHashes",
      "outputs":[
         {
            "internalType":"bytes32[]",
            "name":"",
            "type":"bytes32[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_streamHash",
            "type":"bytes32"
         }
      ],
      "name":"getStreamData",
      "outputs":[
         {
            "components":[
               {
                  "internalType":"address",
                  "name":"streamer",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"streamerVault",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"recipient",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"recipientVault",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"token",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"amount",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"startingTimestamp",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"duration",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"totalStreamed",
                  "type":"uint256"
               },
               {
                  "internalType":"bool",
                  "name":"recurring",
                  "type":"bool"
               }
            ],
            "internalType":"struct IPayStreams.StreamData",
            "name":"",
            "type":"tuple"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_streamer",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_recipient",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_token",
            "type":"address"
         },
         {
            "internalType":"string",
            "name":"_tag",
            "type":"string"
         }
      ],
      "name":"getStreamHash",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_streamer",
            "type":"address"
         }
      ],
      "name":"getStreamerStreamHashes",
      "outputs":[
         {
            "internalType":"bytes32[]",
            "name":"",
            "type":"bytes32[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_token",
            "type":"address"
         }
      ],
      "name":"isSupportedToken",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"renounceOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint16",
            "name":"_feeInBasisPoints",
            "type":"uint16"
         }
      ],
      "name":"setFeeInBasisPoints",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_streamHash",
            "type":"bytes32"
         },
         {
            "components":[
               {
                  "internalType":"bool",
                  "name":"callAfterStreamCreated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeFundsCollected",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterFundsCollected",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeStreamUpdated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterStreamUpdated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeStreamClosed",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterStreamClosed",
                  "type":"bool"
               }
            ],
            "internalType":"struct IPayStreams.HookConfig",
            "name":"_hookConfig",
            "type":"tuple"
         }
      ],
      "name":"setHookConfigForStream",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "components":[
               {
                  "internalType":"address",
                  "name":"streamer",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"streamerVault",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"recipient",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"recipientVault",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"token",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"amount",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"startingTimestamp",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"duration",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"totalStreamed",
                  "type":"uint256"
               },
               {
                  "internalType":"bool",
                  "name":"recurring",
                  "type":"bool"
               }
            ],
            "internalType":"struct IPayStreams.StreamData",
            "name":"_streamData",
            "type":"tuple"
         },
         {
            "components":[
               {
                  "internalType":"bool",
                  "name":"callAfterStreamCreated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeFundsCollected",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterFundsCollected",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeStreamUpdated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterStreamUpdated",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callBeforeStreamClosed",
                  "type":"bool"
               },
               {
                  "internalType":"bool",
                  "name":"callAfterStreamClosed",
                  "type":"bool"
               }
            ],
            "internalType":"struct IPayStreams.HookConfig",
            "name":"_streamerHookConfig",
            "type":"tuple"
         },
         {
            "internalType":"string",
            "name":"_tag",
            "type":"string"
         }
      ],
      "name":"setStream",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_token",
            "type":"address"
         },
         {
            "internalType":"bool",
            "name":"_support",
            "type":"bool"
         }
      ],
      "name":"setToken",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_streamHash",
            "type":"bytes32"
         },
         {
            "internalType":"address",
            "name":"_vault",
            "type":"address"
         }
      ],
      "name":"setVaultForStream",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"transferOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_streamHash",
            "type":"bytes32"
         },
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_startingTimestamp",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_duration",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"_recurring",
            "type":"bool"
         }
      ],
      "name":"updateStream",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   }
] as const