# Feature request

## Prerequisites

Please ensure that the feature you are requesting for is relevant, and does not stray away too far from the project goals.

## Describe

Describe your proposed feature in detail and how it  would help. Does it solve an issue, or is it supposed to be a useful addition?

## Effects

How would the feature affect the current state of the project? Does it require drastic architectural changes?

## Additional details

Explain how you would go about implementing the feature.